// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaintERP.Data;

#nullable disable

namespace PaintERP.Migrations
{
    [DbContext(typeof(PaintErpDbContext))]
    [Migration("20260719130909_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaintERP.Models.Entities.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("VendorId");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 25000m,
                            BillDate = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = 1,
                            IsPaid = false,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 17000m,
                            BillDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = 1,
                            IsPaid = false,
                            VendorId = 2
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Industry = "Industrial Coatings",
                            LogoUrl = "/images/logos/painterp-logo.svg",
                            Name = "USA Paint ERP",
                            PrimaryColor = "#0A5C9E"
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LifetimeValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Email = "finance@coastalbuilders.us",
                            Industry = "Construction",
                            LifetimeValue = 560000m,
                            Name = "Coastal Builders"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            Email = "ap@evergreenretail.com",
                            Industry = "Retail",
                            LifetimeValue = 420000m,
                            Name = "Evergreen Retail"
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 62000m,
                            CompanyId = 1,
                            CustomerId = 1,
                            InvoiceDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPaid = false
                        },
                        new
                        {
                            Id = 2,
                            Amount = 48000m,
                            CompanyId = 1,
                            CustomerId = 2,
                            InvoiceDate = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPaid = true
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.PaintItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorFamily")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("PaintItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorFamily = "Blue",
                            ColorHex = "#0D47A1",
                            Name = "Patriot Blue High Gloss",
                            ReorderLevel = 150,
                            StockQuantity = 420,
                            UnitCost = 45m,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 2,
                            ColorFamily = "Red",
                            ColorHex = "#C62828",
                            Name = "Liberty Red Latex",
                            ReorderLevel = 120,
                            StockQuantity = 280,
                            UnitCost = 38m,
                            WarehouseId = 2
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.ProductionOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("ProductionOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatchNumber = "PB-2407",
                            CompanyId = 1,
                            ProductName = "Patriot Blue High Gloss",
                            ProductionDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quantity = 1200,
                            Status = "Mixing"
                        },
                        new
                        {
                            Id = 2,
                            BatchNumber = "LR-2406",
                            CompanyId = 1,
                            ProductName = "Liberty Red Latex",
                            ProductionDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quantity = 900,
                            Status = "Quality Check"
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("VendorId");

                    b.ToTable("PurchaseOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            OrderDate = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Awaiting Approval",
                            TotalAmount = 29000m,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            OrderDate = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Approved",
                            TotalAmount = 18000m,
                            VendorId = 2
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.SalesOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("SalesOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Open",
                            TotalAmount = 85000m
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Fulfilled",
                            TotalAmount = 42000m
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OutstandingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Raw Materials",
                            CompanyId = 1,
                            Email = "orders@titanpigments.com",
                            Name = "Titan Pigments",
                            OutstandingAmount = 82000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Packaging",
                            CompanyId = 1,
                            Email = "billing@northshorepack.com",
                            Name = "Northshore Packaging",
                            OutstandingAmount = 31000m
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Location = "Dallas, TX",
                            Name = "Dallas Main"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            Location = "Atlanta, GA",
                            Name = "Atlanta Distribution"
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Bill", b =>
                {
                    b.HasOne("PaintERP.Models.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaintERP.Models.Entities.Vendor", "Vendor")
                        .WithMany("Bills")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Customer", b =>
                {
                    b.HasOne("PaintERP.Models.Entities.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Invoice", b =>
                {
                    b.HasOne("PaintERP.Models.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaintERP.Models.Entities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.PaintItem", b =>
                {
                    b.HasOne("PaintERP.Models.Entities.Warehouse", "Warehouse")
                        .WithMany("PaintItems")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.ProductionOrder", b =>
                {
                    b.HasOne("PaintERP.Models.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("PaintERP.Models.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaintERP.Models.Entities.Vendor", "Vendor")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.SalesOrder", b =>
                {
                    b.HasOne("PaintERP.Models.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaintERP.Models.Entities.Customer", "Customer")
                        .WithMany("SalesOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Vendor", b =>
                {
                    b.HasOne("PaintERP.Models.Entities.Company", "Company")
                        .WithMany("Vendors")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Warehouse", b =>
                {
                    b.HasOne("PaintERP.Models.Entities.Company", "Company")
                        .WithMany("Warehouses")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Company", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Vendors");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Vendor", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Warehouse", b =>
                {
                    b.Navigation("PaintItems");
                });
#pragma warning restore 612, 618
        }
    }
}
