// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaintERP.Data;

#nullable disable

namespace PaintERP.Migrations
{
    [DbContext(typeof(PaintErpDbContext))]
    [Migration("20260719140231_UpdateVendorEntity")]
    partial class UpdateVendorEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaintERP.Models.Entities.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("VendorId");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 25000m,
                            BillDate = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = 1,
                            IsPaid = false,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 17000m,
                            BillDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = 1,
                            IsPaid = false,
                            VendorId = 2
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Industry = "Industrial Coatings",
                            LogoUrl = "/images/logos/painterp-logo.svg",
                            Name = "USA Paint ERP",
                            PrimaryColor = "#0A5C9E"
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LifetimeValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Email = "finance@coastalbuilders.us",
                            Industry = "Construction",
                            LifetimeValue = 560000m,
                            Name = "Coastal Builders"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            Email = "ap@evergreenretail.com",
                            Industry = "Retail",
                            LifetimeValue = 420000m,
                            Name = "Evergreen Retail"
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 62000m,
                            CompanyId = 1,
                            CustomerId = 1,
                            InvoiceDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPaid = false
                        },
                        new
                        {
                            Id = 2,
                            Amount = 48000m,
                            CompanyId = 1,
                            CustomerId = 2,
                            InvoiceDate = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPaid = true
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.PaintItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorFamily")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("PaintItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorFamily = "Blue",
                            ColorHex = "#0D47A1",
                            Name = "Patriot Blue High Gloss",
                            ReorderLevel = 150,
                            StockQuantity = 420,
                            UnitCost = 45m,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 2,
                            ColorFamily = "Red",
                            ColorHex = "#C62828",
                            Name = "Liberty Red Latex",
                            ReorderLevel = 120,
                            StockQuantity = 280,
                            UnitCost = 38m,
                            WarehouseId = 2
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.ProductionOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("ProductionOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatchNumber = "PB-2407",
                            CompanyId = 1,
                            ProductName = "Patriot Blue High Gloss",
                            ProductionDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quantity = 1200,
                            Status = "Mixing"
                        },
                        new
                        {
                            Id = 2,
                            BatchNumber = "LR-2406",
                            CompanyId = 1,
                            ProductName = "Liberty Red Latex",
                            ProductionDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quantity = 900,
                            Status = "Quality Check"
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("VendorId");

                    b.ToTable("PurchaseOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            OrderDate = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Awaiting Approval",
                            TotalAmount = 29000m,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            OrderDate = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Approved",
                            TotalAmount = 18000m,
                            VendorId = 2
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.SalesOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("SalesOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Open",
                            TotalAmount = 85000m
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Fulfilled",
                            TotalAmount = 42000m
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AdditionalDocumentsPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("AveragePaymentDays")
                        .HasColumnType("int");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BusinessCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BusinessCountry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BusinessCounty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BusinessLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BusinessState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BusinessStreetAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BusinessSuiteApt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BusinessZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ContactFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactJobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactMobilePhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactOfficePhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DBA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("DefaultDiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("DefaultExpenseAccount")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DefaultTaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("DefaultWarehouse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FederalTaxId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InsuranceCertificatePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InternalNotes")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<bool>("Is1099Vendor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPreferredVendor")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastPurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("int");

                    b.Property<string>("LegalBusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("MinimumOrderQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OpeningBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OutstandingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PreferredPaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PreferredShippingMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RoutingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SalesTaxCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SalesTaxExemptionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("SameAsBusinessAddress")
                        .HasColumnType("bit");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShippingStreetAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShippingZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StateTaxId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SwiftCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalBills")
                        .HasColumnType("int");

                    b.Property<int>("TotalPurchaseOrders")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VendorContractPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VendorRating")
                        .HasColumnType("int");

                    b.Property<DateTime>("VendorSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("W9FormPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "",
                            AccountType = "",
                            AdditionalDocumentsPath = "",
                            AveragePaymentDays = 0,
                            BankName = "",
                            BusinessCity = "",
                            BusinessCountry = "USA",
                            BusinessCounty = "",
                            BusinessLicenseNumber = "",
                            BusinessName = "Titan Pigments",
                            BusinessState = "",
                            BusinessStreetAddress = "",
                            BusinessSuiteApt = "",
                            BusinessZipCode = "",
                            CompanyId = 1,
                            ContactEmail = "orders@titanpigments.com",
                            ContactExtension = "",
                            ContactFirstName = "",
                            ContactJobTitle = "",
                            ContactLastName = "",
                            ContactMobilePhone = "",
                            ContactOfficePhone = "",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            CreditLimit = 0m,
                            Currency = "USD",
                            DBA = "",
                            DefaultDiscountPercent = 0m,
                            DefaultExpenseAccount = "",
                            DefaultTaxRate = 0m,
                            DefaultWarehouse = "",
                            FederalTaxId = "",
                            Industry = "",
                            InsuranceCertificatePath = "",
                            InternalNotes = "",
                            Is1099Vendor = false,
                            IsActive = true,
                            IsPreferredVendor = false,
                            LeadTimeDays = 0,
                            LegalBusinessName = "",
                            MinimumOrderQuantity = 0m,
                            OpeningBalance = 0m,
                            OutstandingAmount = 82000m,
                            PaymentTerms = "Net 30",
                            PreferredPaymentMethod = "Check",
                            PreferredShippingMethod = "",
                            RoutingNumber = "",
                            SalesTaxCode = "",
                            SalesTaxExemptionNumber = "",
                            SameAsBusinessAddress = true,
                            ShippingCity = "",
                            ShippingState = "",
                            ShippingStreetAddress = "",
                            ShippingZipCode = "",
                            StateTaxId = "",
                            SwiftCode = "",
                            TotalBills = 0,
                            TotalPurchaseOrders = 0,
                            UpdatedAtUtc = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "",
                            VendorCategory = "Raw Materials",
                            VendorContractPath = "",
                            VendorId = "VND26-0001",
                            VendorRating = 5,
                            VendorSince = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VendorType = "Supplier",
                            W9FormPath = ""
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "",
                            AccountType = "",
                            AdditionalDocumentsPath = "",
                            AveragePaymentDays = 0,
                            BankName = "",
                            BusinessCity = "",
                            BusinessCountry = "USA",
                            BusinessCounty = "",
                            BusinessLicenseNumber = "",
                            BusinessName = "Northshore Packaging",
                            BusinessState = "",
                            BusinessStreetAddress = "",
                            BusinessSuiteApt = "",
                            BusinessZipCode = "",
                            CompanyId = 1,
                            ContactEmail = "billing@northshorepack.com",
                            ContactExtension = "",
                            ContactFirstName = "",
                            ContactJobTitle = "",
                            ContactLastName = "",
                            ContactMobilePhone = "",
                            ContactOfficePhone = "",
                            CreatedAtUtc = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            CreditLimit = 0m,
                            Currency = "USD",
                            DBA = "",
                            DefaultDiscountPercent = 0m,
                            DefaultExpenseAccount = "",
                            DefaultTaxRate = 0m,
                            DefaultWarehouse = "",
                            FederalTaxId = "",
                            Industry = "",
                            InsuranceCertificatePath = "",
                            InternalNotes = "",
                            Is1099Vendor = false,
                            IsActive = true,
                            IsPreferredVendor = false,
                            LeadTimeDays = 0,
                            LegalBusinessName = "",
                            MinimumOrderQuantity = 0m,
                            OpeningBalance = 0m,
                            OutstandingAmount = 31000m,
                            PaymentTerms = "Net 30",
                            PreferredPaymentMethod = "Check",
                            PreferredShippingMethod = "",
                            RoutingNumber = "",
                            SalesTaxCode = "",
                            SalesTaxExemptionNumber = "",
                            SameAsBusinessAddress = true,
                            ShippingCity = "",
                            ShippingState = "",
                            ShippingStreetAddress = "",
                            ShippingZipCode = "",
                            StateTaxId = "",
                            SwiftCode = "",
                            TotalBills = 0,
                            TotalPurchaseOrders = 0,
                            UpdatedAtUtc = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "",
                            VendorCategory = "Packaging",
                            VendorContractPath = "",
                            VendorId = "VND26-0002",
                            VendorRating = 5,
                            VendorSince = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VendorType = "Supplier",
                            W9FormPath = ""
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Location = "Dallas, TX",
                            Name = "Dallas Main"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            Location = "Atlanta, GA",
                            Name = "Atlanta Distribution"
                        });
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Bill", b =>
                {
                    b.HasOne("PaintERP.Models.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaintERP.Models.Entities.Vendor", "Vendor")
                        .WithMany("Bills")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Customer", b =>
                {
                    b.HasOne("PaintERP.Models.Entities.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Invoice", b =>
                {
                    b.HasOne("PaintERP.Models.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaintERP.Models.Entities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.PaintItem", b =>
                {
                    b.HasOne("PaintERP.Models.Entities.Warehouse", "Warehouse")
                        .WithMany("PaintItems")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.ProductionOrder", b =>
                {
                    b.HasOne("PaintERP.Models.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("PaintERP.Models.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaintERP.Models.Entities.Vendor", "Vendor")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.SalesOrder", b =>
                {
                    b.HasOne("PaintERP.Models.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaintERP.Models.Entities.Customer", "Customer")
                        .WithMany("SalesOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Vendor", b =>
                {
                    b.HasOne("PaintERP.Models.Entities.Company", "Company")
                        .WithMany("Vendors")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Warehouse", b =>
                {
                    b.HasOne("PaintERP.Models.Entities.Company", "Company")
                        .WithMany("Warehouses")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Company", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Vendors");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Vendor", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("PaintERP.Models.Entities.Warehouse", b =>
                {
                    b.Navigation("PaintItems");
                });
#pragma warning restore 612, 618
        }
    }
}
